title: default
'@extends':
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            uikit.accordion:
              name: uikit_accordion
              label: UIKIT.ACCORDION
              help: UIKIT.ACCORDION_HELP
              type: list
              fields:
                .title:
                  name: accordion_title
                  label: UIKIT.OPTION.TITLE
                  type: text
                .content:
                  name: accordion_content
                  label: UIKIT.OPTION.CONTENT
                  type: editor
                .active:
                  name: accordion_active
                  label: UIKIT.OPTION.ACTIVE
                  type: toggle
                  default: 0
                  options:
                    0: GENERAL.NO
                    1: GENERAL.YES
                  validate:
                    type: bool
                .animation:
                  name: accordion_animation
                  label: UIKIT.OPTION.ANIMATION
                  help: UIKIT.ACCORDION.ANIMATION_HELP
                  type: toggle
                  default: 1
                  options:
                    0: GENERAL.NO
                    1: GENERAL.YES
                  validate:
                    type: bool
                .duration:
                  name: accordion_duration
                  label: UIKIT.OPTION.DURATION
                  type: number
                  default: 200
                .transition:
                  name: accordion_transition
                  label: UIKIT.OPTION.TRANSITION
                  type: select
                  classes: fancy
                  default: 'ease'
                  options:
                    ease: 'ease'
                    linear: 'linear'
                    ease-in: 'ease-in'
                    ease-in-out: 'ease-in-out'
                    ease-out: 'ease-out'
                  validate:
                    type: bool
                .collapsible:
                  name: accordion_collapsible
                  label: UIKIT.OPTION.COLLAPSIBLE
                  type: toggle
                  default: 1
                  options:
                    0: GENERAL.NO
                    1: GENERAL.YES
                  validate:
                    type: bool
                .multiple:
                  name: accordion_multiple
                  label: UIKIT.OPTION.MULTIPLE
                  type: toggle
                  default: 1
                  options:
                    0: GENERAL.NO
                    1: GENERAL.YES
                  validate:
                    type: bool
                .class:
                  name: accordion_class
                  label: UIKIT.OPTION.CLASS
                  type: selectize
                  selectize:
                    options:
                      - text: "test"
                        value: "real value 1"
                      - text: "test-2"
                        value: "real value 2"
                      - text: "test-3"
                        value: "real value 3"
                  size: large
                  classes: fancy
                  validate:
                    type: commalist
                # missing: content, targets, toggle
            uikit.card:
              name: uikit_card
              label: UIKIT.CARD
              help: UIKIT.CARD_HELP
              type: list
              fields:
                .title:
                  name: card_title
                  label: UIKIT.OPTION.TITLE
                  type: text
                .content:
                  name: card_content
                  label: UIKIT.OPTION.CONTENT
                  type: editor
                .sections:
                  name: card_sections
                  label: UIKIT.CARD.SECTIONS
                  type: fieldset
                  title: Your title
                  help: Help text
                  info: Info text
                  text: Text inside fieldset and before other fields
                  icon: comments       # Fork Awesome icons system (see : forkaweso.me).
                  collapsed: true      # Initial state of fieldset (see collapsible option)
                  collapsible: true    # Whether one can expand the fieldset or not
                  fields:
                    .sections.header:
                      name: card_header
                      label: UIKIT.OPTION.HEADER_CONTENT
                      type: editor
                    .sections.footer:
                      name: card_footer
                      label: UIKIT.OPTION.FOOTER_CONTENT
                      type: editor
                .image:
                  name: card_image
                  label: UIKIT.OPTION.IMAGE
                  type: pagemediaselect
                  multiple: true
                .imageposition:
                  name: card_imageposition
                  label: UIKIT.OPTION.IMAGEPOSITION
                  type: select
                  default: top
                  options:
                    top: "uk-card-media-top"
                    bottom: "uk-card-media-bottom"
                    left: "uk-card-media-left"
                    right: "uk-card-media-right"
                .badge:
                  name: card_badge
                  label: UIKIT.CARD.BADGE
                  type: fieldset
                  title: Your title
                  help: Help text
                  info: Info text
                  text: Text inside fieldset and before other fields
                  icon: comments       # Fork Awesome icons system (see : forkaweso.me).
                  collapsed: true      # Initial state of fieldset (see collapsible option)
                  collapsible: true    # Whether one can expand the fieldset or not
                  fields:
                    .badge.title:
                      name: card_badge_title
                      label: UIKIT.OPTION.BADGE_TITLE
                      type: text
                    .badge.icon:
                      name: card_footer
                      label: UIKIT.OPTION.BADGE_ICON
                      type: selectize
                      selectize:
                        options:
                          - text: "check"
                            value: "check"
                          - text: "heart"
                            value: "heart"
                      size: large
                      classes: fancy
                      validate:
                        type: commalist
                .class:
                  name: card_class
                  label: UIKIT.OPTION.CLASS
                  type: selectize
                  selectize:
                    options:
                      - text: "uk-card-default"
                        value: "uk-card-default"
                      - text: "uk-card-primary"
                        value: "uk-card-primary"
                      - text: "uk-card-secondary"
                        value: "uk-card-secondary"
                      - text: "uk-card-hover"
                        value: "uk-card-hover"
                      - text: "uk-card-small"
                        value: "uk-card-small"
                      - text: "uk-card-large"
                        value: "uk-card-large"
                  size: large
                  classes: fancy
                  validate:
                    type: commalist
            uikit.lightbox:
              name: uikit_lightbox
              label: UIKIT.LIGHTBOX
              help: UIKIT.LIGHTBOX_HELP
              type: list
              fields: 
                .animation:
                  name: lightbox_animation
                  label: UIKIT.OPTION.ANIMATION
                  type: select
                  classes: fancy
                  default: 'slide'
                  options:
                    slide: 'slide'
                    fade: 'fade'
                    scale: 'ease-in'
                  validate:
                    type: bool
                .autoplayoptions:
                  name: lightbox_autoplayoptions
                  label: UIKIT.LIGHTBOX.AUTOPLAYOPTIONS
                  type: fieldset
                  title: UIKIT.LIGHTBOX.AUTOPLAYOPTIONS
                  help: UIKIT.LIGHTBOX.AUTOPLAYOPTIONS_HELP
                  info: UIKIT.LIGHTBOX.AUTOPLAYOPTIONS_INFO
                  text: UIKIT.LIGHTBOX.AUTOPLAYOPTIONS_TEXT
                  icon: play       # Fork Awesome icons system (see : forkaweso.me).
                  collapsed: true      # Initial state of fieldset (see collapsible option)
                  collapsible: true    # Whether one can expand the fieldset or not
                  fields:
                    .autoplay:
                      name: lightbox_autoplay
                      label: UIKIT.OPTION.AUTOPLAY
                      type: number
                      default: 0
                    .autoplayinterval:
                      name: lightbox_autoplayinterval
                      label: UIKIT.OPTION.AUTOPLAYINTERVAL
                      type: number
                      default: 0
                    .pauseonhover:
                      name: lightbox_pauseonhover
                      label: UIKIT.OPTION.PAUSEONHOVER
                      type: toggle
                      default: 0
                      options:
                        0: GENERAL.NO
                        1: GENERAL.YES
                      validate:
                        type: bool
                    .videoautoplay:
                      name: lightbox_videoautoplay
                      label: UIKIT.OPTION.VIDEOAUTOPLAY
                      type: toggle
                      default: 0
                      options:
                        0: GENERAL.NO
                        1: GENERAL.YES
                      validate:
                        type: bool
                .slides:
                  name: lightbox_slides
                  label: UIKIT.OPTION.SLIDES
                  help: UIKIT.OPTION.SLIDES_HELP
                  type: list
                  fields:
                    .images:
                      type: file
                      label: UIKIT.LIGHTBOX.SLIDES
                      multiple: true
                      accept:
                        - image/*
                        - .mp4
                    .youtube:
                      type: text
                    .vimeo:
                      type: text
                    .googlemap:
                      type: text
                .initializer:
                  name: lightbox_initializer
                  label: UIKIT.LIGHTBOX.INITIALIZER
                  type: select
                  classes: fancy
                  default: 'link'
                  options:
                    link: 'link'
                    image: 'image'
                  validate:
                    type: bool
            uikit.marker:
              name: marker
              type: list
              label: UIKIT.MARKER
              fields:
                .image:
                  name: marker_image
                  type: pagemediaselect
                  label: UIKIT.OPTION.MARKER_IMAGE
                .x:
                  name: marker_x
                  type: text
                  label: UIKIT.OPTION.MARKER_X
                .y:
                  name: marker_y
                  type: text
                  label: UIKIT.OPTION.MARKER_Y
                .tooltip:
                  name: marker_tooltip
                  type: text
                  label: UIKIT.OPTION.MARKER_DESCRIPTION
            uikit.switcher:
              name: switcher
              type: list
              label: UIKIT.SWITCHER
            